[package]
name = "uniffi-bindgen"
authors = ["Elias Rohrer <dev@tnull.de>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
uniffi = { version = "0.29.0", features = ["cli"] }
